## Tensorflow v2 - Basic Operations

In [8]:
import tensorflow as tf

print(f"Tensorflow version: {tf.__version__}")

Tensorflow version: 2.11.0


In [7]:
a = tf.constant(2)
b = tf.constant(3)

In [9]:
tf.print(a + b)

5


In [10]:
tf.print(a * b)

6


In [23]:
add = tf.math.add(a, b)
mul = tf.math.multiply(a, b)

tf.Tensor(5, shape=(), dtype=int32)


In [24]:
print(add)
print(mul)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [26]:
matrix1 = tf.constant([[3., 3.]])
print(matrix1)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)


In [27]:
matrix2 = tf.constant([[2.],[2.]])
print(matrix2)

tf.Tensor(
[[2.]
 [2.]], shape=(2, 1), dtype=float32)


In [29]:
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>